
import { Lesson, QuestionType } from './types';

export const LESSONS: Lesson[] = [
  {
    id: 'lesson-1',
    title: '第一課：選班長',
    description: '🍭 學習 u 行韻母 (ua, uo, uai, uei, uan, uen, uang, ueng) 🍬',
    questions: [
      { id: 101, type: QuestionType.MC, context: '「水準」🌊', prompt: '「水」的韻母是？', options: [{id: 'A', text: 'uei'}, {id: 'B', text: 'ui'}, {id: 'C', text: 'uai'}], correctAnswer: 'A' },
      { id: 102, type: QuestionType.MC, context: '「嘴唇」👄', prompt: '「唇」的韻母是？', options: [{id: 'A', text: 'un'}, {id: 'B', text: 'uen'}, {id: 'C', text: 'uan'}], correctAnswer: 'B' },
      { id: 103, type: QuestionType.MC, context: '「退婚」💍', prompt: '「退」的韻母是？', options: [{id: 'A', text: 'uei'}, {id: 'B', text: 'ui'}, {id: 'C', text: 'uai'}], correctAnswer: 'A' },
      { id: 104, type: QuestionType.MC, context: '「退婚」💍', prompt: '「婚」的韻母是？', options: [{id: 'A', text: 'uen'}, {id: 'B', text: 'un'}, {id: 'C', text: 'uan'}], correctAnswer: 'A' },
      { id: 105, type: QuestionType.MC, context: '「嘴唇」👄', prompt: '「嘴」的韻母是？', options: [{id: 'A', text: 'uei'}, {id: 'B', text: 'ui'}], correctAnswer: 'A' },
      { id: 106, type: QuestionType.MC, context: '辨析 🧐', prompt: '下列哪個字的韻母中含有「u」音？', options: [{id: 'A', text: '選舉'}, {id: 'B', text: '辦事'}, {id: 'C', text: '水準'}], correctAnswer: 'C' },
      { id: 107, type: QuestionType.MC, context: '「國」🇨🇳', prompt: '「國」的韻母是？', options: [{id: 'A', text: 'uo'}, {id: 'B', text: 'o'}], correctAnswer: 'A' },
      { id: 108, type: QuestionType.MC, context: '「乖」👧', prompt: '「乖」的韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'ai'}], correctAnswer: 'A' },
      { id: 109, type: QuestionType.MC, context: '「翁」👴', prompt: '「翁」的韻母是？', options: [{id: 'A', text: 'ueng'}, {id: 'B', text: 'eng'}], correctAnswer: 'A' },
      { id: 110, type: QuestionType.MC, context: '「花」🌸', prompt: '「花」的韻母是？', options: [{id: 'A', text: 'ua'}, {id: 'B', text: 'uo'}], correctAnswer: 'A' },
      { id: 111, type: QuestionType.MC, context: '「睡」😴', prompt: '「睡」的韻母是？', options: [{id: 'A', text: 'uei'}, {id: 'B', text: 'ei'}], correctAnswer: 'A' },
      { id: 112, type: QuestionType.MC, context: '「短」📏', prompt: '「短」的韻母是？', options: [{id: 'A', text: 'uan'}, {id: 'B', text: 'an'}], correctAnswer: 'A' },
      { id: 113, type: QuestionType.MC, context: '「黃」💛', prompt: '「黃」的韻母是？', options: [{id: 'A', text: 'uang'}, {id: 'B', text: 'ang'}], correctAnswer: 'A' },
      { id: 114, type: QuestionType.MC, context: '「對」✅', prompt: '「對」的韻母是？', options: [{id: 'A', text: 'uei'}, {id: 'B', text: 'ei'}], correctAnswer: 'A' },
      { id: 115, type: QuestionType.MC, context: '「春」🌱', prompt: '「春」的韻母是？', options: [{id: 'A', text: 'uen'}, {id: 'B', text: 'un'}], correctAnswer: 'A' },
      { id: 116, type: QuestionType.MC, context: '「刷」🪥', prompt: '「刷」的韻母是？', options: [{id: 'A', text: 'ua'}, {id: 'B', text: 'a'}], correctAnswer: 'A' },
      { id: 117, type: QuestionType.MC, context: '「桌」🪑', prompt: '「桌」的韻母是？', options: [{id: 'A', text: 'uo'}, {id: 'B', text: 'e'}], correctAnswer: 'A' },
      { id: 118, type: QuestionType.MC, context: '「問」❓', prompt: '「問」的韻母是？', options: [{id: 'A', text: 'uen'}, {id: 'B', text: 'an'}], correctAnswer: 'A' },
      { id: 119, type: QuestionType.MC, context: '「廣」🗺️', prompt: '「廣」的韻母是？', options: [{id: 'A', text: 'uang'}, {id: 'B', text: 'ang'}], correctAnswer: 'A' },
      { id: 120, type: QuestionType.MC, context: '「朵」☁️', prompt: '「朵」的韻母是？', options: [{id: 'A', text: 'uo'}, {id: 'B', text: 'o'}], correctAnswer: 'A' },
    ]
  },
  {
    id: 'lesson-2',
    title: '第二課：跨學科學習日',
    description: '🍓 掌握 uai / uei 辨析與關鍵對應詞 🍰',
    questions: [
      { id: 201, type: QuestionType.MC, context: '對比 👽', prompt: '「外來」的「外」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'A' },
      { id: 202, type: QuestionType.MC, context: '對比 🚀', prompt: '「未來」的「未」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'B' },
      { id: 203, type: QuestionType.MC, context: '對比 🕵️', prompt: '「怪人」的「怪」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'A' },
      { id: 204, type: QuestionType.MC, context: '對比 👑', prompt: '「貴人」的「貴」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'B' },
      { id: 205, type: QuestionType.MC, context: '對比 🤗', prompt: '「懷抱」的「懷」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'A' },
      { id: 206, type: QuestionType.MC, context: '對比 💰', prompt: '「回報」的「回」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'B' },
      { id: 207, type: QuestionType.MC, context: '對比 😤', prompt: '「不快」的「快」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'A' },
      { id: 208, type: QuestionType.MC, context: '對比 ✨', prompt: '「不愧」的「愧」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'B' },
      { id: 209, type: QuestionType.MC, context: '聽音找詞 🎯', prompt: '「guài zuì」對應哪個詞？', options: [{id: 'A', text: '怪罪'}, {id: 'B', text: '快慰'}, {id: 'C', text: '毀壞'}], correctAnswer: 'A' },
      { id: 210, type: QuestionType.MC, context: '聽音找詞 🎯', prompt: '「kuài wèi」對應哪個詞？', options: [{id: 'A', text: '怪罪'}, {id: 'B', text: '快慰'}, {id: 'C', text: '毀壞'}], correctAnswer: 'B' },
      { id: 211, type: QuestionType.MC, context: '聽音找詞 🎯', prompt: '「huǐ huài」對應哪個詞？', options: [{id: 'A', text: '怪罪'}, {id: 'B', text: '快慰'}, {id: 'C', text: '毀壞'}], correctAnswer: 'C' },
      { id: 212, type: QuestionType.MC, context: '「帥」🕶️', prompt: '「帥」的韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'A' },
      { id: 213, type: QuestionType.MC, context: '「誰」❓', prompt: '「誰」的韻母是？', options: [{id: 'A', text: 'uei'}, {id: 'B', text: 'uai'}], correctAnswer: 'A' },
      { id: 214, type: QuestionType.MC, context: '「塊」🧱', prompt: '「塊」的韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'A' },
      { id: 215, type: QuestionType.MC, context: '「推」👐', prompt: '「推」的韻母是？', options: [{id: 'A', text: 'uei'}, {id: 'B', text: 'uai'}], correctAnswer: 'A' },
      { id: 216, type: QuestionType.MC, context: '「壞」🏚️', prompt: '「壞」的韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'A' },
      { id: 217, type: QuestionType.MC, context: '「追」🏃', prompt: '「追」的韻母是？', options: [{id: 'A', text: 'uei'}, {id: 'B', text: 'uai'}], correctAnswer: 'A' },
      { id: 218, type: QuestionType.MC, context: '辨析 ✍️', prompt: '「快」的正確認讀是？', options: [{id: 'A', text: 'kuài'}, {id: 'B', text: 'kuì'}], correctAnswer: 'A' },
      { id: 219, type: QuestionType.MC, context: '辨析 ✍️', prompt: '「愧」的正確認讀是？', options: [{id: 'A', text: 'kuài'}, {id: 'B', text: 'kuì'}], correctAnswer: 'B' },
      { id: 220, type: QuestionType.MC, context: '「外」🚪', prompt: '「窗外」的「外」韻母是？', options: [{id: 'A', text: 'uai'}, {id: 'B', text: 'uei'}], correctAnswer: 'A' },
    ]
  },
  {
    id: 'lesson-3',
    title: '第三課：燒烤樂',
    description: '🍖 熟練 uan, uen, uang 的組合辨析 🌭',
    questions: [
      { id: 301, type: QuestionType.MC, context: '「一萬」💰', prompt: '「萬」的韻母是？', options: [{id: 'A', text: 'uan'}, {id: 'B', text: 'uang'}], correctAnswer: 'A' },
      { id: 302, type: QuestionType.MC, context: '「船邊」⚓', prompt: '「船」的韻母是？', options: [{id: 'A', text: 'uan'}, {id: 'B', text: 'uang'}], correctAnswer: 'A' },
      { id: 303, type: QuestionType.MC, context: '「疑問」🤔', prompt: '「問」的韻母是？', options: [{id: 'A', text: 'uen'}, {id: 'B', text: 'un'}], correctAnswer: 'A' },
      { id: 304, type: QuestionType.MC, context: '「唇邊」💄', prompt: '「唇」的韻母是？', options: [{id: 'A', text: 'uen'}, {id: 'B', text: 'uan'}], correctAnswer: 'A' },
      { id: 305, type: QuestionType.MC, context: '「遺忘」🕯️', prompt: '「忘」的韻母是？', options: [{id: 'A', text: 'uang'}, {id: 'B', text: 'ang'}], correctAnswer: 'A' },
      { id: 306, type: QuestionType.MC, context: '「床邊」🏠', prompt: '「床」的韻母是？', options: [{id: 'A', text: 'uang'}, {id: 'B', text: 'ang'}], correctAnswer: 'A' },
      { id: 307, type: QuestionType.MC, context: '對比 🍲', prompt: '「端著」的正確認讀是？', options: [{id: 'A', text: 'duān zhe'}, {id: 'B', text: 'dūn zhe'}], correctAnswer: 'A' },
      { id: 308, type: QuestionType.MC, context: '對比 🧘', prompt: '「蹲著」的正確認讀是？', options: [{id: 'A', text: 'duān zhe'}, {id: 'B', text: 'dūn zhe'}], correctAnswer: 'B' },
      { id: 309, type: QuestionType.MC, context: '對比 🏢', prompt: '「專員」的正確認讀是？', options: [{id: 'A', text: 'zhuān yuán'}, {id: 'B', text: 'zhuāng yuán'}], correctAnswer: 'A' },
      { id: 310, type: QuestionType.MC, context: '對比 🏰', prompt: '「莊園」的正確認讀是？', options: [{id: 'A', text: 'zhuān yuán'}, {id: 'B', text: 'zhuāng yuán'}], correctAnswer: 'B' },
      { id: 311, type: QuestionType.MC, context: '音節 🌟', prompt: '「guāng huán」對應哪個詞？', options: [{id: 'A', text: '光環'}, {id: 'B', text: '黃昏'}, {id: 'C', text: '溫暖'}], correctAnswer: 'A' },
      { id: 312, type: QuestionType.MC, context: '音節 🌇', prompt: '「huáng hūn」對應哪個詞？', options: [{id: 'A', text: '光環'}, {id: 'B', text: '黃昏'}, {id: 'C', text: '溫暖'}], correctAnswer: 'B' },
      { id: 313, type: QuestionType.MC, context: '音節 🧶', prompt: '「wēn nuǎn」對應哪個詞？', options: [{id: 'A', text: '光環'}, {id: 'B', text: '黃昏'}, {id: 'C', text: '溫暖'}], correctAnswer: 'C' },
      { id: 314, type: QuestionType.MC, context: '「鬆軟」🧸', prompt: '「軟」的韻母是？', options: [{id: 'A', text: 'uan'}, {id: 'B', text: 'un'}], correctAnswer: 'A' },
      { id: 315, type: QuestionType.MC, context: '「雙手」👐', prompt: '「雙」的韻母是？', options: [{id: 'A', text: 'uang'}, {id: 'B', text: 'ang'}], correctAnswer: 'A' },
      { id: 316, type: QuestionType.MC, context: '「短髮」📏', prompt: '「短」的韻母是？', options: [{id: 'A', text: 'uan'}, {id: 'B', text: 'an'}], correctAnswer: 'A' },
      { id: 317, type: QuestionType.MC, context: '「陽光」✨', prompt: '「光」的韻母是？', options: [{id: 'A', text: 'uang'}, {id: 'B', text: 'uan'}], correctAnswer: 'A' },
      { id: 318, type: QuestionType.MC, context: '「討論」🗣️', prompt: '「論」的韻母（未省略前）是？', options: [{id: 'A', text: 'uen'}, {id: 'B', text: 'un'}], correctAnswer: 'A' },
      { id: 319, type: QuestionType.MC, context: '「酸甜」🍋', prompt: '「酸」的韻母是？', options: [{id: 'A', text: 'uan'}, {id: 'B', text: 'an'}], correctAnswer: 'A' },
      { id: 320, type: QuestionType.MC, context: '「寬廣」🌉', prompt: '「寬」的韻母是？', options: [{id: 'A', text: 'uan'}, {id: 'B', text: 'uang'}], correctAnswer: 'A' },
    ]
  },
  {
    id: 'bonus',
    title: 'bonus超級混合',
    description: '🎉 隨機 20 題混合挑戰，只有最強的拼音達人能通關！ 🏆',
    questions: []
  }
];
